"""
(ALMOST) COMPLETELY GENERATED BY CLAUDE. NOT MY OWN CODE


Airport Runway Timeline Generator
===================================
Visualises per-flight arrival, landing, turnaround and takeoff
on a horizontal Gantt-style timeline and saves it as a PNG image.

Usage
-----
    python airport_timeline.py

Customise the `planes` list near the bottom of the file, or call
`render_timeline(planes, output_path)` from your own code.

Data format
-----------
Each plane is a dict with:
    id      – flight identifier string  (e.g. "KL1234")
    arrives – expected arrival time     (HH:MM string, 24-h)
    lands   – actual landing time       (HH:MM string, 24-h)

Constants
---------
    TURNAROUND_MIN  – fixed turnaround time in minutes (default 55)
    RUNWAY_GAP_MIN  – minimum gap between successive takeoffs (default 5)
"""

from __future__ import annotations
import math
import matplotlib
matplotlib.use("Agg")          # headless – no display needed
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyArrow
from matplotlib.lines import Line2D
import matplotlib.ticker as ticker

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TURNAROUND_MIN = 55   # fixed turnaround time
RUNWAY_GAP_MIN = 5    # clearance between successive takeoffs

# ---------------------------------------------------------------------------
# Colour palette  (matches the web prototype)
# ---------------------------------------------------------------------------
C_WAIT    = "#378ADD"   # waiting in air
C_GROUND  = "#1D9E75"   # on ground / turnaround
C_HELD    = "#B4B2A9"   # ready but runway occupied
C_LAND    = "#0C447C"   # landing marker
C_READY   = "#085041"   # ready-to-depart marker
C_TAKEOFF = "#D85A30"   # takeoff arrow
C_AXIS    = "#888780"   # grid / axis
C_LABEL   = "#444441"   # flight ID label
C_TIME    = "#5F5E5A"   # small time annotations
C_BG_ALT  = "#F1EFE8"   # alternating row tint


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------
def to_mins(t: str) -> int:
    """Convert 'HH:MM' to minutes since midnight."""
    h, m = t.split(":")
    return int(h) * 60 + int(m)


def to_hhmm(mins: int) -> str:
    """Convert minutes since midnight to 'HH:MM'."""
    h = (mins // 60) % 24
    m = mins % 60
    return f"{h:02d}:{m:02d}"


# ---------------------------------------------------------------------------
# Core scheduling logic
# ---------------------------------------------------------------------------
def schedule(planes: list[dict]) -> list[dict]:
    """
    Given raw plane dicts (id, arrives, lands) compute:
        arrM    – arrival in minutes
        landM   – landing in minutes
        readyM  – turnaround complete
        takeoffM– actual takeoff (may be delayed by runway)
    Sorted by landing time; runway serialised with RUNWAY_GAP_MIN gap.
    """
    data = []
    for p in planes:
        data.append({
            "id":    p["id"],
            "arrM":  to_mins(p["arrives"]),
            "landM": to_mins(p["lands"]),
            "readyM": to_mins(p["lands"]) + TURNAROUND_MIN,
        })

    data.sort(key=lambda d: d["landM"])

    runway_free = 0
    for d in data:
        takeoff = max(d["readyM"], runway_free)
        d["takeoffM"] = takeoff
        runway_free = takeoff + RUNWAY_GAP_MIN

    return data


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------
def render_timeline(
    planes: list[dict],
    output_path: str = "runway_timeline.png",
    dpi: int = 150,
) -> None:
    """Render and save the runway timeline image."""

    # data = schedule(planes)
    data = planes
    n = len(data)

    # --- figure geometry ---
    ROW_H   = 0.7      # height of each row in data-units
    ROW_GAP = 0.3      # vertical gap between rows
    ROW_STEP = ROW_H + ROW_GAP

    fig_h = max(4.0, n * ROW_STEP + 1.8)
    fig_w = 14.0

    fig, ax = plt.subplots(figsize=(fig_w, fig_h), dpi=dpi)
    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")

    # --- time axis range ---
    all_mins = [v for d in data for v in (d["arrM"], d["landM"], d["readyM"], d["takeoffM"])]
    t_min = math.floor(min(all_mins) / 10) * 10 - 10
    t_max = math.ceil(max(all_mins) / 10) * 10 + 20
    ax.set_xlim(t_min, t_max)
    ax.set_ylim(-0.5, n * ROW_STEP)

    # --- grid lines ---
    tick_step = 10 if (t_max - t_min) <= 120 else 20 if (t_max - t_min) <= 240 else 30
    for m in range(t_min, t_max + 1, tick_step):
        ax.axvline(m, color=C_AXIS, linewidth=0.4, alpha=0.5, zorder=0)

    # --- x-axis labels ---
    ax.set_xticks(range(t_min, t_max + 1, tick_step))
    ax.set_xticklabels(
        [to_hhmm(m) for m in range(t_min, t_max + 1, tick_step)],
        fontsize=8, color=C_TIME,
    )
    ax.tick_params(axis="x", which="both", length=3, color=C_AXIS)
    ax.xaxis.set_ticks_position("top")
    ax.xaxis.set_label_position("top")

    # --- y axis off ---
    ax.yaxis.set_visible(False)
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.spines["top"].set_visible(True)
    ax.spines["top"].set_color(C_AXIS)
    ax.spines["top"].set_linewidth(0.6)

    # --- draw each row ---
    BAR_H  = ROW_H * 0.55   # bar thickness (fraction of row height)
    MARKER = ROW_H * 0.85   # diamond / landing marker height

    for i, d in enumerate(data):
        y_center = (n - 1 - i) * ROW_STEP + ROW_H / 2

        # alternating row background
        if i % 2 == 0:
            ax.barh(
                y_center, t_max - t_min, height=ROW_STEP * 0.98,
                left=t_min, color=C_BG_ALT, alpha=0.4, zorder=0,
            )

        # --- flight ID label ---
        ax.text(
            t_min - 1, y_center, d["id"],
            ha="right", va="center", fontsize=9,
            fontweight="bold", color=C_LABEL,
        )

        # helper: draw a horizontal bar
        def hbar(start, end, color, alpha=1.0, zorder=2):
            w = end - start
            if w <= 0:
                return
            ax.barh(
                y_center, w, height=BAR_H,
                left=start, color=color, alpha=alpha,
                zorder=zorder, linewidth=0,
            )

        # 1. waiting in air  (arrives → lands)
        if d["arrM"] < d["landM"]:
            hbar(d["arrM"], d["landM"], C_WAIT)

        # 2. turnaround on ground  (lands → ready)
        hbar(d["landM"], d["readyM"], C_GROUND)

        # 3. held on ground  (ready → takeoff, if delayed)
        if d["takeoffM"] > d["readyM"]:
            hbar(d["readyM"], d["takeoffM"], C_HELD)

        # --- arrival marker (circle) ---
        ax.plot(
            d["arrM"], y_center, "o",
            color=C_WAIT, markersize=7, markeredgecolor="white",
            markeredgewidth=1, zorder=4,
        )

        # --- landing marker (vertical rectangle) ---
        lx = d["landM"]
        ax.plot(
            [lx, lx],
            [y_center - MARKER / 2, y_center + MARKER / 2],
            color=C_LAND, linewidth=3, solid_capstyle="round", zorder=5,
        )

        # --- ready marker (circle with ring) ---
        ax.plot(
            d["readyM"], y_center, "o",
            color=C_READY, markersize=7,
            markeredgecolor=C_GROUND, markeredgewidth=1.5, zorder=4,
        )

        # --- takeoff marker (triangle / arrow) ---
        tx = d["takeoffM"]
        tri_h = MARKER * 0.9
        tri_w = tri_h * 0.55
        triangle = plt.Polygon(
            [
                [tx,           y_center + tri_h / 2],
                [tx + tri_w,   y_center],
                [tx,           y_center - tri_h / 2],
            ],
            closed=True, color=C_TAKEOFF, zorder=5,
        )
        ax.add_patch(triangle)

        # --- time annotations ---
        def ann(mins, label=None, x_offset=0, y_offset=None, color=C_TIME, size=7.5, ha="center"):
            txt = label if label is not None else to_hhmm(mins)
            yo = (BAR_H / 2 + 0.07) if y_offset is None else y_offset
            ax.text(
                mins + x_offset, y_center + yo, txt,
                ha=ha, va="bottom", fontsize=size, color=color,
            )

        ann(d["arrM"])
        ann(d["landM"], color=C_LAND)
        ann(d["readyM"])
        ann(d["takeoffM"], x_offset=tri_w + 1, y_offset=0,
            ha="left", color=C_TAKEOFF, size=8)

    # --- legend ---
    legend_elements = [
        mpatches.Patch(color=C_WAIT,    label="Waiting in air"),
        mpatches.Patch(color=C_GROUND,  label=f"On ground / turnaround ({TURNAROUND_MIN} min)"),
        mpatches.Patch(color=C_HELD,    label="Ready — runway occupied"),
        Line2D([0], [0], color=C_LAND,    linewidth=2.5, label="Landing"),
        Line2D([0], [0], marker="o",      color="w", markerfacecolor=C_READY,
               markersize=7, markeredgecolor=C_GROUND,
               markeredgewidth=1.5, label="Turnaround complete"),
        mpatches.Patch(color=C_TAKEOFF, label="Takeoff"),
    ]
    ax.legend(
        handles=legend_elements,
        loc="lower right",
        fontsize=7.5,
        framealpha=0.9,
        edgecolor=C_AXIS,
        ncol=2,
    )

    # --- title ---
    fig.suptitle(
        "Airport Runway Timeline",
        fontsize=13, fontweight="bold", color=C_LABEL, y=0.995,
    )

    plt.tight_layout(rect=[0, 0, 1, 0.995])
    fig.savefig(output_path, bbox_inches="tight", dpi=dpi)
    plt.close(fig)
    print(f"Saved: {output_path}")


# ---------------------------------------------------------------------------
# Sample data  – edit this section or replace with your computed data
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    planes = [
        {"id": "KL1234", "arrives": "08:00", "lands": "08:10"},
        {"id": "EZY456", "arrives": "08:20", "lands": "08:45"},
        {"id": "BA789",  "arrives": "08:30", "lands": "09:05"},
        {"id": "TK202",  "arrives": "09:00", "lands": "09:30"},
        {"id": "FR055",  "arrives": "09:15", "lands": "09:55"},
        {"id": "LH301",  "arrives": "10:05", "lands": "10:20"},
    ]

    render_timeline(planes, output_path="runway_timeline.png", dpi=150)
